#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v18
# autospec commit: f35655a
#
Name     : R-RANN
Version  : 2.6.2
Release  : 52
URL      : https://cran.r-project.org/src/contrib/RANN_2.6.2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/RANN_2.6.2.tar.gz
Summary  : Fast Nearest Neighbour Search (Wraps ANN Library) Using L2
Group    : Development/Tools
License  : GPL-3.0
Requires: R-RANN-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
given dataset in O(N log N) time using Arya and Mount's ANN library
    (v1.1.3). There is support for approximate as well as exact searches,
    fixed radius searches and 'bd' as well as 'kd' trees. The distance is
    computed using the L2 (Euclidean) metric. Please see package 'RANN.L1'
    for the same functionality using the L1 (Manhattan, taxicab) metric.

%package lib
Summary: lib components for the R-RANN package.
Group: Libraries

%description lib
lib components for the R-RANN package.


%prep
%setup -q -n RANN
pushd ..
cp -a RANN buildavx2
popd
pushd ..
cp -a RANN buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1724604614

%install
export SOURCE_DATE_EPOCH=1724604614
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/RANN/COPYRIGHT
/usr/lib64/R/library/RANN/DESCRIPTION
/usr/lib64/R/library/RANN/INDEX
/usr/lib64/R/library/RANN/Meta/Rd.rds
/usr/lib64/R/library/RANN/Meta/features.rds
/usr/lib64/R/library/RANN/Meta/hsearch.rds
/usr/lib64/R/library/RANN/Meta/links.rds
/usr/lib64/R/library/RANN/Meta/nsInfo.rds
/usr/lib64/R/library/RANN/Meta/package.rds
/usr/lib64/R/library/RANN/NAMESPACE
/usr/lib64/R/library/RANN/NEWS.md
/usr/lib64/R/library/RANN/R/RANN
/usr/lib64/R/library/RANN/R/RANN.rdb
/usr/lib64/R/library/RANN/R/RANN.rdx
/usr/lib64/R/library/RANN/help/AnIndex
/usr/lib64/R/library/RANN/help/RANN.rdb
/usr/lib64/R/library/RANN/help/RANN.rdx
/usr/lib64/R/library/RANN/help/aliases.rds
/usr/lib64/R/library/RANN/help/paths.rds
/usr/lib64/R/library/RANN/html/00Index.html
/usr/lib64/R/library/RANN/html/R.css
/usr/lib64/R/library/RANN/tests/testthat.R
/usr/lib64/R/library/RANN/tests/testthat/test-nn.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/RANN/libs/RANN.so
/V4/usr/lib64/R/library/RANN/libs/RANN.so
/usr/lib64/R/library/RANN/libs/RANN.so
